In [1]:
import os
os.chdir('..')

In [2]:
import numpy as np
from instance_generator import sample_instances
import torch_converter as tc
import torch
%load_ext autoreload
%autoreload 2

In [3]:
kwargs = {
    'graph_type': 'ER',
    'p': 0.5,
    'weighted': True
}

instances = sample_instances(m=3, n=2, num=3, rng=np.random.default_rng(), args={}, **kwargs)

In [48]:
neighbors = tc._neighbor_encoder(instances[0])
print(neighbors)

tensor([[ True,  True,  True],
        [ True, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True]])


In [44]:
tc._active_encoder(instances[0])

AttributeError: module 'torch_converter' has no attribute '_active_encoder'

In [60]:
neighbors = torch.tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [False, False, True],
        [False, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [False, True, False],
        [False, False, False],
        [True, False, False],
        [ True,  True,  True]])

In [9]:
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.loader import DataLoader
from torch_converter import _instances_to_train_samples

class MatchingData(Data):
    def __cat_dim__(self, key, value, *args, **kwargs):
        if key == 'neighbors':
            return None
        if key == 'm':
            return None
        else:
            return super().__cat_dim__(key, value, *args, **kwargs)
        

instances = sample_instances(3, 2, 2, np.random.default_rng(), {}, **kwargs)
data_ = [MatchingData(**data) for data in _instances_to_train_samples(instances, 'regression', None)]
data = DataLoader(data_, batch_size=2)

In [10]:
for dat in data:
    print(dat)

MatchingDataBatch(x=[12, 5], edge_index=[2, 20], edge_attr=[20, 1], m=[2, 1], hint=[4], t=[2], neighbors=[2, 6, 3], n=[2], batch=[12], ptr=[3])
MatchingDataBatch(x=[12, 5], edge_index=[2, 18], edge_attr=[18, 1], m=[2, 1], hint=[5], t=[2], neighbors=[2, 6, 3], n=[2], batch=[12], ptr=[3])


In [8]:
data_

[MatchingData(x=[6, 5], edge_index=[2, 10], edge_attr=[10, 1], m=[1], hint=[2], t=0, neighbors=[6, 3], n=[1]),
 MatchingData(x=[6, 5], edge_index=[2, 6], edge_attr=[6, 1], m=[1], hint=[2], t=1, neighbors=[6, 3], n=[1]),
 MatchingData(x=[6, 5], edge_index=[2, 14], edge_attr=[14, 1], m=[1], hint=[2], t=0, neighbors=[6, 3], n=[1]),
 MatchingData(x=[6, 5], edge_index=[2, 4], edge_attr=[4, 1], m=[1], hint=[2], t=2, neighbors=[6, 3], n=[1])]

In [103]:
test=neighbors.reshape(2, 6, 3)
test[torch.arange(test.size(0)), :, index].T

[autoreload of util failed: Traceback (most recent call last):
  File "/Users/wikum/miniconda3/envs/core/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "/Users/wikum/miniconda3/envs/core/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 475, in superreload
    module = reload(module)
             ^^^^^^^^^^^^^^
  File "/Users/wikum/miniconda3/envs/core/lib/python3.11/importlib/__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'util'
]


tensor([[ True,  True],
        [ True,  True],
        [False, False],
        [ True, False],
        [False,  True],
        [ True,  True]])

In [82]:
index = torch.tensor([2, 0])

In [102]:
indices = index.unsqueeze(1).unsqueeze(2)
indices = torch.repeat_interleave(indices, 6, dim=1)
print(indices)
torch.gather(test, 2, indices).squeeze().T

tensor([[[2],
         [2],
         [2],
         [2],
         [2],
         [2]],

        [[0],
         [0],
         [0],
         [0],
         [0],
         [0]]])


tensor([[ True,  True],
        [ True,  True],
        [False, False],
        [ True, False],
        [False,  True],
        [ True,  True]])

In [57]:
neighbors[:, index]

tensor([[ True,  True],
        [ True,  True],
        [False, False],
        [False, False],
        [False, False],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [False, False],
        [False, False],
        [False, False],
        [ True,  True]])

In [58]:
neighbors

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True]])